# Generated by Django 5.2.1 on 2025-06-27 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('adresse_siege', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='entreprises_images/')),
                ('entreprise_infos', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='application_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='application_users', to='auth.permission')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='appOWA1.entreprise')),
                ('roles', models.ManyToManyField(blank=True, null=True, related_name='utilisateurs', to='appOWA1.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texte_brut', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_classe', models.BooleanField(default=False)),
                ('formations', models.TextField(blank=True, null=True)),
                ('experiences', models.TextField(blank=True, null=True)),
                ('competences', models.TextField(blank=True, null=True)),
                ('langues', models.TextField(blank=True, null=True)),
                ('permis_conduite', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
                ('metier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='appOWA1.metier')),
            ],
        ),
        migrations.CreateModel(
            name='CV_classe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metiers', models.JSONField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_classes', to='appOWA1.cv')),
            ],
        ),
        migrations.CreateModel(
            name='OffresEmploi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metier_propose', models.CharField(max_length=100)),
                ('secteur_activite', models.CharField(max_length=100)),
                ('Experience_requise', models.CharField(max_length=100)),
                ('niveau_etude', models.CharField(max_length=100)),
                ('type_contrat', models.CharField(max_length=100)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('profil_recherche', models.TextField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='appOWA1.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='CV_Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOWA1.cv')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOWA1.offresemploi')),
            ],
            options={
                'unique_together': {('cv', 'offre')},
            },
        ),
        migrations.AddField(
            model_name='cv',
            name='offres',
            field=models.ManyToManyField(blank=True, null=True, related_name='cvs', through='appOWA1.CV_Offre', to='appOWA1.offresemploi'),
        ),
    ]
