# Generated by Django 5.2.1 on 2025-06-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOWA1', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metier',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
