# Generated by Django 5.2.1 on 2025-06-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOWA1', '0003_alter_metier_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv_offre',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score de test'),
        ),
    ]
